theme: jekyll-theme-slate
title: Guiding Principles
description: for Hearing Allyship
google_analytics: UA-120430598-1
github:
  owner_name: the Deaf community
  owner_url: https://www.youtube.com/watch?v=MoxVdw6T0LA
